package uk.gov.ukho.ais.lambda.heatmap.job.model.validation;

public enum ValidationFailure {
  JOB_CONFIG_DOES_NOT_EXIST,
  JOB_CONFIG_NOT_VALID_JSON,
  JOB_CONFIG_DOES_NOT_HAVE_YEAR,
  JOB_CONFIG_DOES_NOT_HAVE_MONTH,
  JOB_CONFIG_DOES_NOT_HAVE_FILTER_SQL_FILE,
  FILTER_SQL_FILE_DOES_NOT_EXIST,
  JOB_CONFIG_CONTAINS_INVALID_MONTH,
  JOB_CONFIG_CONTAINS_INVALID_YEAR,
  OUTPUT_S3_BUCKET_DOES_NOT_EXIST,
  JOB_CONFIG_DOES_NOT_HAVE_OUTPUT
}
