image: gradle:5.4-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - gradle clean assemble

test:
  stage: test
  script:
    - gradle clean check test
