image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  stage: test
  script:
    - ./gradlew clean check test

build:
  stage: build
  script:
    - ./gradlew clean assemble
