variables:
  poolName: "UKHO Ubuntu 1804"

resources:
  containers:
    - container: jdk
      image: ukhydrographicoffice/jdk8-python36

stages:
  - stage: CI
    jobs:
      - job: build
        pool: $(poolName)
        container: jdk
        steps:
          - bash: ./gradlew clean assemble
            displayName: 'Run Gradle `assemble` task'

      - job: check
        pool: $(poolName)
        container: jdk
        steps:
          - bash: ./gradlew clean check
            displayName: 'Run Gradle `check` task'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              TF_VAR_PASSWORD: $(TF_VAR_PASSWORD)

          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'ukho-sonarcloud'
              organization: 'ukho'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'UKHO_spark-ais-to-raster'
              cliProjectName: 'ais-to-raster'
              cliSources: '.'
              extraProperties: 'sonar.java.binaries=**/**'

          - task: SonarCloudAnalyze@1

      - job: test
        pool: $(poolName)
        container: jdk
        steps:
          - bash: ./gradlew clean test
            displayName: 'Run Gradle `test` task'
