version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew clean assemble

  check:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew --continue clean check aggregateReports
      - store_artifacts:
          path:  ./build/reports

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew clean test

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew clean terraformApply --auto-approve

workflows:
  version: 2

  ci:
    jobs:
      - build
      - check
      - test
      - deploy:
          requires:
            - build
            - check
            - test
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check
